org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.parallel=false
net.minecraftforge.gradle.merge-source-sets=false

minecraft_version=1.10.2
minecraft_version_range=[1.10.2]
forge_version=12.18.3.2511
forge_version_range=[12.18.3.2511,)
loader_version_range=[12,)
mapping_channel=stable
mapping_version=29-1.10.2

loader_name=forge
loader_code=1
java_version=8
java_toolchain_version=8.0.502+7
java_setup_version=8.0.502+7
gradle_java_version=17
curseforge_project_id=240984

mod_id=steamadvantage
mod_name=Steam Advantage
mod_license=GPL-3.0-only
mod_version=2.2.3.110021
mod_group=com.mcmoddev.steamadvantage
mod_authors=DrCyano
mod_description=Steam-powered machines and infrastructure for the Power Advantage platform.

cf_requirements=power-advantage,base-metals
cf_optionals=
cf_versions=1.10.2

poweradvantage_version=2.4.2.110021
poweradvantage_source_repository=MinecraftModDevelopmentMods/PowerAdvantage
poweradvantage_source_ref=18e5192b73c6768208c1d5c5687ea230ed470bc6
poweradvantage_deobf_sha256=84F26845E7A161A7062B2C44522115B2C253F4B2329E55B568B290C215EDD78D
orespawn_version=4.0.8.110021
orespawn_source_repository=MinecraftModDevelopmentMods/OreSpawn
orespawn_source_commit=5a50df1158e948c8db55814e819090b34c12d765
orespawn_deobf_sha256=33BFB8C9D626D071147A0952A74B633F0BCC6A27E0408B4524370F4833B003C2
